Vagrant.configure("2") do |config|
    # Specify the base box for the VM
    config.vm.box = "centos/7"
  
    # Provision the VM using a shell script named "provision.sh"
    config.vm.provision "shell", path: "provision.sh"
  end
  