Vagrant.configure("2") do |config|
    # Define a box base para a VM, neste caso, usando CentOS 7
    config.vm.box = 'centos/7'
  
    # Define o nome do host da VM como 'manager'
    config.vm.hostname = 'manager'
  
    # Cria uma rede privada com um endereço IP específico
    config.vm.network "private_network", ip: "192.168.1.2"
  
    # Configura as propriedades do provedor de máquina virtual, como a quantidade de memória
    config.vm.provider 'virtualbox' do |v| 
      v.memory = 2048
    end
  end
  