Vagrant.configure("2") do |config|
    # Define a box base para a VM, neste caso, usando CentOS 7
    config.vm.box = 'centos/7'
  
    # Define o nome do host da VM como 'sonarqube'
    config.vm.hostname = 'sonarqube'
  
    # Configura port forwarding para acessar SonarQube na VM através da porta 9000 no host
    config.vm.network 'forwarded_port', guest: 9000, host: 9000, hostip: '127.0.0.1'
  
    # Cria uma rede privada com um endereço IP específico
    config.vm.network "private_network", ip: "192.168.1.6"
  
    # Provê o provisionamento da VM usando um script shell chamado 'provision.sh'
    config.vm.provision 'shell', path: 'provision.sh'
  
    # Configura as propriedades do provedor de máquina virtual, como a quantidade de memória
    config.vm.provider 'virtualbox' do |v| 
      v.memory = 1024
    end
  end
  