#vagrant init [box_name]: Initializes a new Vagrantfile in the current directory, using the specified box (optional).
#vagrant up: Starts the virtual machine according to the Vagrantfile in the current directory.
#vagrant halt: Shuts down the virtual machine.
#vagrant reload: Restarts the virtual machine, loading any changes made to the Vagrantfile.
#vagrant ssh: Connects to the virtual machine via SSH.
#vagrant status: Displays the current status of the virtual machine.
#vagrant suspend: Suspends the execution of the virtual machine, saving its current state to memory.
#vagrant resume: Resumes the execution of a suspended virtual machine.
#vagrant destroy: Completely removes the virtual machine.
#vagrant provision: Re-runs the provisioning configuration defined in the Vagrantfile.
#vagrant global-status: Displays the status of all Vagrant-managed virtual machines across all projects.
#vagrant box list: Lists all available Vagrant boxes locally on the system.
#vagrant box add [name] [URL]: Adds a new Vagrant box locally to the system.
#vagrant box remove [name]: Removes a Vagrant box from the system.
#vagrant package: Creates a new Vagrant box from the current state of the virtual machine.

Vagrant.configure("2") do |config|
  # Specify the base box to use for the VM, in this case CentOS 7
  config.vm.box = "centos/7"
  
  # Forward port 8080 on the host to port 80 on the guest (VM)
  config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  
  # Sync a local folder named "html" to the guest folder "/home/vagrant/data_guest", creating it if it doesn't exist
  config.vm.synced_folder "html", "/home/vagrant/data_guest", create: true
  
  # Configure shell provisioner to run the provision.sh script during VM setup
  config.vm.provision "shell", path: "provision.sh"
end
