Vagrant.configure("2") do |config|
  # Specify the base box for the VM
  config.vm.box = "centos/7"

  # Set the hostname of the VM
  config.vm.hostname = "db01"

  # Create a private network with a specific IP address
  config.vm.network "private_network", ip: "192.168.1.4"

  # Forward a port from the guest VM to the host machine
  config.vm.network "forwarded_port", guest: 3306, host: 3306

  # Provision the VM using a shell script
  config.vm.provision "shell", path: "provision.sh"
end
